Fixes for latest Visual Studio 2017 compiler
The latest VS2017 compiler ("C/C++ Optimizing Compiler Version 19.16.27040 for x64", bundled with "VisualStudio.15.Release/15.9.23+28307.1146") was issuing compilation errors for certain alias templates. The errors were:

hiddenargfunctor.h(16): error C3546: '...': there are no parameter packs available to expand
hiddenargfunctor.h(18): note: see reference to alias template instantiation 'ply::HiddenArgFunctor<Return(Args...)>::FnType<void>' being compiled
hiddenargfunctor.h(34): note: see reference to class template instantiation 'ply::HiddenArgFunctor<Return(Args...)>' being compiled
hiddenargfunctor.h(18): error C3520: 'Args': parameter pack must be expanded in this context
hiddenargfunctor.h(22): error C3520: 'Args': parameter pack must be expanded in this context
...
stringreader.h(17): error C2064: term does not evaluate to a function taking 0 arguments
stringreader.h(116): note: see reference to alias template instantiation 'ply::fmt::TypeFormat<Type>' being compiled

I don't fully understand what might have been wrong with the code, especially since it has worked with every other C++ compiler so far. Regardless, this commit avoids the errors by eliminating the alias templates that triggered them.

(Note: Up to this point, I had been compiling with "C/C++ Optimizing Compiler Version 19.15.26730 for x64" bundled with "VisualStudio.15.Release/15.8.7+28010.2046", and the errors did not occur using that compiler.)